default:
  navigation:
    - title: Marki
      subtitle: Kategorie
      url: /t/marki
      items:
        - :title: Brand A
          :url: /t/marki
        - :title: Brand B
          :url: /t/marki
        - :title: Brand C
          :url: /t/marki
        - :title: Brand D
          :url: /t/marki
        - :title: Brand E
          :url: /t/marki
        - :title: Brand F
          :url: /t/marki
        - :title: Brand G
          :url: /t/marki
        - :title: Brand H
          :url: /t/marki
        - :title: Brand I
          :url: /t/marki
        - :title: Brand J
          :url: /t/marki
        - :title: Brand K
          :url: /t/marki
      promo_banners:
        - subtitle: Wielkie Otwarcie
          title: Przeglądaj Według Marki
          url: /t/marki
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Bestseller
          title: tylko 49 zł
          url: /t/marki/test-brand
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Twarz
      subtitle: Kategorie
      url: /t/twarz
      items:
        - :title: Kremy / Serum
          :url: /t/twarz/kremy-serum
        - :title: Kremy Pod Oczy
          :url: /t/twarz/kremy-pod-oczy
        - :title: DEMAKIJAŻ
          :url: /t/twarz/Demakijaz
        - :title: MASKI
          :url: /t/twarz/maski
        - :title: PEELING
          :url: /t/twarz/peeling
        - :title: INNE
          :url: /t/twarz/inne
      promo_banners:
        - subtitle: Wielkie Otwarcie
          title: Przeglądaj Według Produktów Do Twarzy
          url: /t/twarz
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Bestseller
          title: tylko 58 zł
          url: /t/twarz/test-twarz
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: CIAŁO
      subtitle: Kategorie
      url: /t/cialo
      items:
        - :title: BALSAMY
          :url: /t/cialo/balsamy
        - :title: KĄPIEL / PRYSZNIC
          :url: /t/cialo/kapiel-prtsznic
        - :title: DO RĄK I STÓP
          :url: /t/cialo/do-rak-i-stop
        - :title: HIGIENA INTYMNA
          :url: /t/cialo/higiena-intymna
        - :title: DEPILACJA
          :url: /t/cialo/depilacja      
        - :title: OPALANIE
          :url: /t/cialo/opalanie
      promo_banners:
        - subtitle: Wielkie Otwarcie
          title: Przeglądaj Według Produktów Do Ciała
          url: /t/cialo
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Bestseller
          title: tylko 100 zł
          url: /t/cialo/test-cialo
          image: 'meganav/promo_banner_right-third-category.jpg'
    - title: WŁOSY
      subtitle: Kategorie
      url: /t/wlosy
      items:
        - :title: SZAMPONY
          :url: /t/wlosy/szampony
        - :title: ODŻYWKI I MASKI
          :url: /t/wlosy/odzywki-i-maski
        - :title: OLEJKI
          :url: /t/wlosy/olejki
        - :title: KOLORYZACJA
          :url: /t/wlosy/koloryzacja
        - :title: STYLIZACJA
          :url: /t/wlosy/stylizacja
        - :title: DLA MĘŻCZYZN
          :url: /t/wlosy/dla-mezczyzn
        - :title: AKCESORIA
          :url: /t/wlosy/akcesoria
      promo_banners:
        - subtitle: Wielkie Otwarcie
          title: Przeglądaj Według Produktów Do Włosów
          url: /t/wlosy
          image: 'meganav/promo_banner_left-fourth-category.jpg'
        - subtitle: Bestseller
          title: tylko 23 zł
          url: /t/wlosy/test-wlosy
          image: 'meganav/promo_banner_right-fourth-category.jpg'
    - title: PAZNOKCIE
      subtitle: Kategorie
      url: /t/paznokcie
      items:
        - :title: LAKIERY
          :url: /t/paznokcie/lakiery
        - :title: HYBRYDY
          :url: /t/paznokcie/hybrydy
        - :title: ODŻYWKI
          :url: /t/paznokcie/odzywki
        - :title: AKCESORIA
          :url: /t/paznokcie/akcesoria
      promo_banners:
        - subtitle: Wielkie Otwarcie
          title: Przeglądaj Według Produktów Do Paznokci
          url: /t/paznokcie
          image: 'meganav/promo_banner_left-fifth-category.jpg'
        - subtitle: Bestseller
          title: tylko 11 zł
          url: /t/paznokcie/test-paznokcie
          image: 'meganav/promo_banner_right-fifth-category.jpg'
    - title: MAKIJAŻ
      subtitle: Kategorie
      url: /t/makijaz
      items:
        - :title: USTA
          :url: /t/makijaz/usta
        - :title: OCZY
          :url: /t/makijaz/oczy
        - :title: TWARZ
          :url: /t/makijaz/twarz
        - :title: AKCESORIA
          :url: /t/makijaz/akcesoria
      promo_banners:
        - subtitle: Wielkie Otwarcie
          title: Przeglądaj Według Produktów Do Makijażu
          url: /t/makijaz
          image: 'meganav/promo_banner_left-sixth-category.jpg'
        - subtitle: Bestseller
          title: tylko 35 zł
          url: /t/makijaz/test-makijaz
          image: 'meganav/promo_banner_right-sixth-category.jpg'
    - title: ZAPACHY
      subtitle: Kategorie
      url: /t/zapachy
      items:
        - :title: PERFUMY
          :url: /t/zapachy/perfumy
        - :title: ANTYPERSPIRANTY
          :url: /t/zapachy/antyperspiranty
        - :title: MGIEŁKI
          :url: /t/zapachy/mgielki
      promo_banners: 
        - subtitle: Wielkie Otwarcie
          title: Przeglądaj Według Produktów Zapachowych
          url: /t/zapachy
          image: 'meganav/promo_banner_left-seventh-category.jpg'
        - subtitle: Bestseller
          title: tylko 88 zł
          url: /t/zapachy/test-zapachy
          image: 'meganav/promo_banner_right-seventh-category.jpg'
    - title: DZIECI
      subtitle: Kategorie
      url: /t/dzieci
      items:
        - :title: PIELĘGNACJA
          :url: /t/dzieci/pielegnacja
        - :title: OPALANIE
          :url: /t/dzieci/opalanie
      promo_banners:
        - subtitle: Wielkie Otwarcie
          title: Przeglądaj Według Produktów Dla Dzieci
          url: /t/dzieci
          image: 'meganav/promo_banner_left-eighth-category.jpg'
        - subtitle: Bestseller
          title: tylko 7 zł
          url: /t/dzieci/test-dzieci
          image: 'meganav/promo_banner_right-eighth-category.jpg'
    - title: DOM
      subtitle: Kategorie
      url: /t/dom
      items:
        - :title: ŚRODKI CZYSTOŚCI
          :url: /t/dom/srodki-czystosci
        - :title: AKCESORIA
          :url: /t/dom/akcesoria
      promo_banners:
        - subtitle: Wielkie Otwarcie
          title: Przeglądaj Według Produktów Domowych
          url: /t/dom
          image: 'meganav/promo_banner_left-ninth-category.jpg'
        - subtitle: Bestseller
          title: tylko 10 zł
          url: /t/dom/test-dom
          image: 'meganav/promo_banner_right-ninth-category.jpg'